# Translations template for PROJECT.
# Copyright (C) 2025 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2025.
#
#"Project-Id-Version: PROJECT VERSION\n"
#"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
#"POT-Creation-Date: 2025-07-22 15:48-0500\n"
#"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
#"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
#"Language-Team: LANGUAGE <LL@li.org>\n"
#"MIME-Version: 1.0\n"
#"Content-Type: text/plain; charset=utf-8\n"
#"Content-Transfer-Encoding: 8bit\n"
#"Generated-By: Babel 2.16.0\n"

#: __init__.py:189
msgid "Administrators API is active"
msgstr "API de administración activa"

#: __init__.py:196
msgid "API pública activa"
msgstr "API pública activa"

#: api/adminApi/routes.py:49 api/adminApi/routes.py:97
#: api/adminApi/routes.py:134 api/adminApi/routes.py:169
#: api/adminApi/routes.py:213 api/adminApi/routes.py:260
#: api/adminApi/routes.py:294 api/forms/routes.py:34 api/forms/routes.py:87
#: api/forms/routes.py:187 api/forms/routes.py:222 api/forms/routes.py:257
#: api/forms/routes.py:283 api/lists/routes.py:33 api/lists/routes.py:89
#: api/lists/routes.py:124 api/lists/routes.py:185 api/lists/routes.py:226
#: api/llms/routes.py:14 api/llms/routes.py:28 api/llms/routes.py:42
#: api/llms/routes.py:54 api/llms/routes.py:66 api/llms/routes.py:77
#: api/llms/routes.py:88 api/llms/routes.py:99 api/llms/routes.py:111
#: api/llms/routes.py:122 api/llms/routes.py:133 api/logs/routes.py:49
#: api/logs/routes.py:88 api/records/public_services.py:144
#: api/records/routes.py:52 api/records/routes.py:285
#: api/records/routes.py:326 api/records/routes.py:367
#: api/records/routes.py:632 api/records/routes.py:678
#: api/records/routes.py:718 api/resources/public_services.py:43
#: api/resources/public_services.py:133 api/resources/public_services.py:139
#: api/resources/public_services.py:158 api/resources/public_services.py:216
#: api/resources/public_services.py:219 api/resources/public_services.py:379
#: api/resources/public_services.py:478 api/resources/routes.py:109
#: api/resources/routes.py:125 api/resources/routes.py:215
#: api/resources/routes.py:230 api/resources/routes.py:269
#: api/resources/routes.py:355 api/resources/routes.py:543
#: api/resources/services.py:78 api/resources/services.py:193
#: api/resources/services.py:320 api/resources/services.py:834
#: api/resources/services.py:846 api/resources/services.py:906
#: api/resources/services.py:967 api/resources/services.py:970
#: api/resources/services.py:1143 api/resources/services.py:1201
#: api/resources/services.py:1289 api/resources/services.py:1298
#: api/resources/services.py:1709 api/search/utils/elasticUtils.py:49
#: api/search/utils/elasticUtils.py:51 api/snaps/services.py:96
#: api/snaps/services.py:142 api/system/routes.py:41 api/system/routes.py:69
#: api/system/routes.py:131 api/system/routes.py:156 api/system/routes.py:192
#: api/system/routes.py:219 api/system/routes.py:246 api/system/routes.py:273
#: api/system/routes.py:299 api/system/routes.py:325 api/system/routes.py:351
#: api/system/routes.py:377 api/system/routes.py:425 api/system/routes.py:453
#: api/system/routes.py:480 api/system/routes.py:521 api/system/routes.py:548
#: api/tasks/routes.py:52 api/tasks/routes.py:82 api/tasks/routes.py:108
#: api/tasks/routes.py:148 api/types/routes.py:98 api/types/routes.py:157
#: api/types/routes.py:167 api/types/routes.py:221 api/types/routes.py:260
#: api/types/routes.py:294 api/users/routes.py:41 api/users/routes.py:85
#: api/users/routes.py:189 api/users/routes.py:228 api/users/routes.py:432
#: api/users/routes.py:476 api/users/routes.py:516 api/users/routes.py:559
#: api/usertasks/routes.py:46 api/usertasks/routes.py:49
#: api/usertasks/routes.py:86 api/usertasks/routes.py:114
#: api/usertasks/routes.py:136 api/usertasks/routes.py:170
#: api/usertasks/routes.py:211 api/usertasks/services.py:158
#: api/usertasks/services.py:162 api/views/routes.py:33 api/views/routes.py:66
#: api/views/routes.py:97 api/views/routes.py:142
msgid "You don't have the required authorization"
msgstr "No tienes la autorización requerida"

#: api/adminApi/services.py:13
msgid "Unable to get the default cataloging type"
msgstr "No se puede obtener el tipo de catalogación por defecto"

#: api/adminApi/services.py:40 api/users/services.py:613
msgid "Resource not found"
msgstr "Recurso no encontrado"

#: api/adminApi/services.py:48 api/lists/services.py:146
msgid "Option not found"
msgstr "Opción no encontrada"

#: api/auth/services.py:151
msgid "Too many login attempts. Please try again in 10 minutes."
msgstr "Demasiados intentos de inicio de sesión. Por favor, inténtelo de nuevo en 10 minutos."

#: api/auth/services.py:170 api/tasks/services.py:186 api/users/services.py:43
#: api/users/services.py:63 api/users/services.py:81 api/users/services.py:169
#: api/users/services.py:200 api/users/services.py:575
msgid "User not found"
msgstr "Usuario no encontrado"

#: api/auth/services.py:174
msgid "Invalid password"
msgstr "Contraseña inválida"

#: api/forms/services.py:38
msgid "Text"
msgstr "Texto"

#: api/forms/services.py:42
msgid "Text area"
msgstr "Área de texto"

#: api/forms/services.py:46
msgid "Number"
msgstr "Número"

#: api/forms/services.py:50
msgid "Date"
msgstr "Fecha"

#: api/forms/services.py:54
msgid "Select"
msgstr "Lista de selección"

#: api/forms/services.py:58
msgid "Select multiple"
msgstr "Lista de selección múltiple"

#: api/forms/services.py:62
msgid "Checkbox"
msgstr "Verdadero/Falso"

#: api/forms/services.py:66
msgid "File"
msgstr "Archivo"

#: api/forms/services.py:70
msgid "Repeater"
msgstr "Campo múltiple"

#: api/forms/services.py:74
msgid "Separator"
msgstr "Separador"

#: api/forms/services.py:78
msgid "Author"
msgstr "Autor"

#: api/forms/services.py:82
msgid "Location"
msgstr "Ubicación"

#: api/forms/services.py:86
msgid "User list"
msgstr "Lista de usuarios"

#: api/forms/services.py:157
msgid "Form created successfully"
msgstr "Formulario creado con éxito"

#: api/forms/services.py:200 api/forms/services.py:222
#: api/forms/services.py:412 api/types/services.py:325
msgid "Form not found"
msgstr "Estándar de metadatos no encontrado"

#: api/forms/services.py:211
msgid ""
"Form updated successfully. If new fields were added or the type of any "
"existing fields was changed, it is important to regenerate the index from "
"the option in the system settings"
msgstr "Formulario actualizado con éxito"

#: api/forms/services.py:227
msgid "The form is being used by a post type"
msgstr "El formulario está siendo utilizado por un tipo de publicación"

#: api/forms/services.py:240
msgid "Form deleted successfully"
msgstr "Formulario eliminado con éxito"

#: api/forms/services.py:251
msgid "Error: the field must have a label"
msgstr "Error: el campo debe tener una etiqueta"

#: api/forms/services.py:253
msgid "Error: the field label cannot be empty"
msgstr "Error: la etiqueta del campo no puede estar vacía"

#: api/forms/services.py:256
msgid "Error: the field cannot have destiny equal to ident"
msgstr "Error: el campo no puede tener destino igual a ident"

#: api/forms/services.py:259
msgid "Error: the field destiny must start with metadata"
msgstr "Error: el destino del campo debe comenzar con metadata"

#: api/forms/services.py:264
msgid ""
"Error: the field with destiny equal to metadata.firstLevel.title must be of "
"type text"
msgstr "Error: el campo con destino igual a metadata.firstLevel.title debe ser de tipo texto"

#: api/forms/services.py:268
msgid "Error: the field with type file must have the filetag attribute"
msgstr "Error: el campo con tipo archivo debe tener el atributo filetag"

#: api/forms/services.py:272
msgid "Error: the field with type repeater must have the subfields attribute"
msgstr "Error: el campo con tipo repetidor debe tener el atributo subfields"

#: api/forms/services.py:274
msgid "Error: the subfields attribute must be a list"
msgstr "Error: el atributo subfields debe ser una lista"

#: api/forms/services.py:276
msgid "Error: the subfields attribute cannot be empty"
msgstr "Error: el subcampo no puede estar vacío"

#: api/forms/services.py:280
msgid "Error: the subfield must have a destiny"
msgstr "Error: el subcampo debe tener un destino"

#: api/forms/services.py:282
msgid "Error: the subfield must have a name"
msgstr "Error: el subcampo debe tener un nombre"

#: api/forms/services.py:284
msgid "Error: the subfield must have a type"
msgstr "Error: el subcampo debe tener un tipo"

#: api/forms/services.py:304
msgid "The value of the accessRights field is not valid"
msgstr "Error: el valor del campo accessRights no es válido"

#: api/forms/services.py:309
msgid ""
"Error: the form must have a field with destiny equal to "
"metadata.firstLevel.title"
msgstr "Error: el formulario debe tener un campo con destino igual a metadata.firstLevel.title"

#: api/forms/services.py:340 api/forms/services.py:352
msgid "Error: el campo {field} tiene dos tipos diferentes"
msgstr "Error: el campo {field} tiene dos tipos diferentes"

#: api/forms/services.py:367
msgid "Error: the destiny of the field {field} is repeated"
msgstr "Error: el destino del campo {field} está repetido"

#: api/forms/services.py:374
msgid "The field {field} has two different types"
msgstr "Error: el campo {field} tiene dos tipos diferentes"

#: api/forms/services.py:414
msgid " (copy)"
msgstr ""

#: api/geosystem/services.py:93
msgid "Shapes uploaded successfully"
msgstr "Formas subidas con éxito"

#: api/geosystem/services.py:171 api/system/tasks/elasticTasks.py:189
#, python-format
msgid "Indexing finished for %(count)s resources"
msgstr "Indexación finalizada para %(count)s recursos"

#: api/lists/services.py:64
msgid "List created successfully"
msgstr "Lista creada con éxito"

#: api/lists/services.py:79 api/lists/services.py:113
#: api/lists/services.py:165
msgid "List not found"
msgstr "Lista no encontrada"

#: api/lists/services.py:157
msgid "Error getting option"
msgstr "Error al obtener la opción"

#: api/lists/services.py:206
msgid "List updated successfully"
msgstr "Lista actualizada con éxito"

#: api/lists/services.py:230
msgid "List deleted successfully"
msgstr "Lista eliminada con éxito"

#: api/llms/utils/BaseLLMProvider.py:18 api/llms/utils/BaseLLMProvider.py:21
msgid "This method should be overridden by subclasses."
msgstr ""

#: api/logs/services.py:32
msgid "Log created successfully"
msgstr "Log creado con éxito"

#: api/logs/services.py:42 api/logs/services.py:159
msgid "Logs not found"
msgstr "Logs no encontrados"

#: api/records/public_services.py:102 api/records/public_services.py:189
msgid "id not defined"
msgstr "id no definido"

#: api/records/public_services.py:104
msgid "index not defined"
msgstr "índice no definido"

#: api/records/public_services.py:138 api/snaps/services.py:36
msgid "Record not found"
msgstr "Archivo no encontrado"

#: api/records/public_services.py:197 api/records/services.py:1023
msgid "Record does not have processing"
msgstr "El registro no tiene procesamiento"

#: api/records/public_services.py:200 api/records/services.py:1026
msgid "Record does not have fileProcessing"
msgstr "El registro no tiene fileProcessing"

#: api/records/public_services.py:203 api/records/services.py:1029
msgid "Record does not have fileProcessing type"
msgstr "El registro no tiene tipo de fileProcessing"

#: api/records/routes.py:579
msgid "You must specify a page"
msgstr "Debes especificar una página"

#: api/records/routes.py:581
msgid "You must specify a block"
msgstr "Debes especificar un bloque"

#: api/records/routes.py:583
msgid "You must specify a slug"
msgstr "Debes especificar un slug"

#: api/records/services.py:110 api/records/services.py:166
#: api/records/services.py:197 api/records/services.py:500
#: api/records/services.py:713 api/records/services.py:749
#: api/records/services.py:781 api/records/services.py:790
#: api/records/services.py:866 api/records/services.py:913
#: api/records/services.py:968
msgid "Record does not exist"
msgstr "El registro no existe"

#: api/records/services.py:184
msgid "Record updated"
msgstr "Registro actualizado"

#: api/records/services.py:201
msgid "Record does not have the resource as parent"
msgstr "El registro no tiene el recurso como padre"

#: api/records/services.py:248
msgid "Parent deleted"
msgstr "Padre eliminado"

#: api/records/services.py:273 api/resources/public_services.py:382
#: api/resources/public_services.py:455 api/resources/public_services.py:482
#: api/resources/services.py:861 api/resources/services.py:870
#: api/resources/services.py:900 api/resources/services.py:1146
#: api/resources/services.py:1204 api/resources/services.py:1328
#: api/resources/services.py:1506 api/resources/services.py:1679
msgid "Resource does not exist"
msgstr "El recurso no existe"

#: api/records/services.py:471
msgid "File type not allowed"
msgstr "Tipo de archivo no permitido"

#: api/records/services.py:505 api/records/services.py:543
#: api/records/services.py:1034
msgid "You do not have permission to view this record"
msgstr "No tienes permiso para ver este registro"

#: api/records/services.py:558 api/records/services.py:1015
msgid "id is missing"
msgstr "id está faltando"

#: api/records/services.py:560
msgid "index is missing"
msgstr "índice está faltando"

#: api/records/services.py:711 api/records/services.py:747
msgid "Block updated"
msgstr "Bloque actualizado"

#: api/records/services.py:779
msgid "Block deleted"
msgstr "Bloque eliminado"

#: api/records/services.py:859 api/records/services.py:907
#: api/records/services.py:962
msgid "You do not have permission to edit this transcription"
msgstr "No tienes permiso para ver este registro"

#: api/records/services.py:868 api/records/services.py:870
#: api/records/services.py:915 api/records/services.py:917
#: api/records/services.py:970 api/records/services.py:972
msgid "Record does not have transcription"
msgstr "El registro no tiene transcripción"

#: api/records/services.py:872 api/records/services.py:919
#: api/records/services.py:974
msgid "Record has not been processed with {slug}"
msgstr ""

#: api/records/services.py:898
msgid "Transcription segment deleted"
msgstr "Segmento de transcripción eliminado"

#: api/records/services.py:953
msgid "Transcription speaker edited"
msgstr "Orador de transcripción editado"

#: api/records/services.py:1003
msgid "Transcription segment edited"
msgstr "Segmento de transcripción editado"

#: api/records/services.py:1012 api/resources/services.py:1194
msgid "Files download isn't active"
msgstr "La descarga de archivos no está activa"

#: api/resources/public_services.py:464 api/resources/services.py:1337
msgid "Resource does not have images"
msgstr "El recurso no tiene imágenes"

#: api/resources/services.py:187
msgid "The metadata is required"
msgstr "Los metadatos son requeridos"

#: api/resources/services.py:284
msgid "Resource created successfully"
msgstr "Recurso creado con éxito"

#: api/resources/services.py:308 api/users/services.py:259
#: api/users/services.py:340
msgid "Error validating fields"
msgstr "Error validando campos"

#: api/resources/services.py:315
msgid "Error validating files"
msgstr "Error validando archivos"

#: api/resources/services.py:395
msgid "Resource updated successfully"
msgstr "Recurso creado con éxito"

#: api/resources/services.py:486
msgid "The resource cannot have itself as parent"
msgstr "El recurso no puede tenerse a sí mismo como padre"

#: api/resources/services.py:491
msgid "The parent resource does not exist"
msgstr "El recurso padre no existe"

#: api/resources/services.py:495
msgid "The resource isn't hierarchical"
msgstr "El recurso no es jerárquico"

#: api/resources/services.py:498
msgid "The resource post type is not allowed to have a parent of this type"
msgstr "El tipo de publicación no puede tener un padre de este tipo"

#: api/resources/services.py:513
msgid "The post type must have a parent"
msgstr "El tipo de publicación debe tener un padre"

#: api/resources/services.py:537 api/resources/services.py:570
#: api/resources/services.py:587 api/resources/services.py:603
#: api/resources/services.py:620 api/resources/services.py:637
#: api/resources/services.py:653 api/resources/services.py:673
#: api/resources/services.py:686 api/resources/services.py:702
#: api/resources/services.py:721 api/resources/services.py:728
#: api/resources/services.py:736 api/resources/services.py:743
#: api/resources/services.py:784 api/system/services.py:234
#: api/system/services.py:250 api/system/services.py:269
#: api/system/services.py:296 api/system/services.py:327
#: api/system/services.py:355 api/users/services.py:377
#: api/users/services.py:388 api/users/services.py:399
msgid "The field {label} is required"
msgstr "El campo {label} es requerido"

#: api/resources/services.py:548
msgid "The field {label} must be a list"
msgstr "El campo {label} debe ser una lista"

#: api/resources/services.py:553
msgid "The field {label} must be a list of dicts"
msgstr "El campo {label} debe ser una lista de diccionarios"

#: api/resources/services.py:617 api/resources/services.py:734
msgid "The field {label} must be a number"
msgstr "El campo {label} debe ser un número"

#: api/resources/services.py:634 api/resources/services.py:741
msgid "The field {label} must be a boolean"
msgstr "El campo {label} debe ser un booleano"

#: api/resources/services.py:667 api/resources/services.py:671
msgid "The field {label} must be a list of users"
msgstr "El campo {label} debe ser una lista de usuarios"

#: api/resources/services.py:770 api/resources/services.py:774
#: api/resources/services.py:776
msgid "There is an error in {label}"
msgstr "Hay un error en {label}"

#: api/resources/services.py:793 api/resources/services.py:803
msgid "The resource must have valid access rights"
msgstr "El recurso debe tener derechos de acceso válidos"

#: api/resources/services.py:825
msgid "The field {label} must have a maximum of {maxFiles} files"
msgstr "El campo {label} debe tener un máximo de {maxFiles} archivos"

#: api/resources/services.py:941
msgid "Asociated files"
msgstr "Archivos asociados"

#: api/resources/services.py:1258
msgid "Zip files deleted"
msgstr "Archivos zip eliminados"

#: api/resources/services.py:1271
msgid "Inventory files deleted"
msgstr "Archivos de inventario eliminados"

#: api/resources/services.py:1319
msgid "Resource deleted"
msgstr "Recurso eliminado"

#: api/resources/services.py:1458
msgid "Post type does not exist"
msgstr "El tipo de publicación no existe"

#: api/resources/services.py:1714
msgid "Post type changed"
msgstr "Tipo de publicación cambiado"

#: api/search/public_services.py:29 api/search/services.py:23
msgid "No response from the indexing system"
msgstr "No hay respuesta del sistema de indexación"

#: api/snaps/services.py:59
msgid "Snap created successfully"
msgstr "Recorte creado con éxito"

#: api/snaps/services.py:83
msgid "Snap updated successfully"
msgstr "Recorte actualizado con éxito"

#: api/snaps/services.py:94 api/snaps/services.py:140
msgid "Snap not found"
msgstr "Recorte no encontrado"

#: api/snaps/services.py:106
msgid "Snap deleted successfully"
msgstr "Recorte eliminado con éxito"

#: api/snaps/services.py:160 api/snaps/services.py:188
msgid "Error while getting the file: {error}"
msgstr "Error al obtener el archivo: {error}"

#: api/snaps/services.py:192 api/snaps/services.py:194
#: api/snaps/services.py:196 api/snaps/services.py:198
#: api/snaps/services.py:200 api/snaps/services.py:207
msgid "File not found"
msgstr "Archivo no encontrado"

#: api/system/services.py:57
msgid "Error while changing the value of the field {key}"
msgstr "Error al cambiar el valor del campo {key}"

#: api/system/services.py:71
msgid "Error while getting the resources: {e}"
msgstr "Error al obtener los recursos: {e}"

#: api/system/services.py:113
msgid "System updates applied successfully"
msgstr "Actualizaciones del sistema aplicadas con éxito"

#: api/system/services.py:129
msgid "There si no default cataloging type"
msgstr "No hay un tipo de catalogación predeterminado"

#: api/system/services.py:136
msgid "Error while getting the default cataloging type"
msgstr "Error al obtener el tipo de catalogación predeterminado"

#: api/system/services.py:150
msgid "The default type of the cataloging module does not exist"
msgstr "El tipo predeterminado del módulo de catalogación no existe"

#: api/system/services.py:157
msgid "Error while getting the default type of the cataloging module"
msgstr "Error al obtener el tipo predeterminado del módulo de catalogación"

#: api/system/services.py:175
msgid "Resources schema updated successfully"
msgstr "Esquema de recursos actualizado con éxito"

#: api/system/services.py:178
msgid "Error while updating the resources schema"
msgstr "Error al actualizar el esquema de recursos"

#: api/system/services.py:191
msgid "There is no resources schema uploaded"
msgstr "No hay un esquema de recursos cargado"

#: api/system/services.py:195
msgid "Error while getting the resources schema"
msgstr "Error al obtener el esquema de recursos"

#: api/system/services.py:214
msgid "Error while getting the value of the field {key}"
msgstr "Error al obtener el valor del campo {key}"

#: api/system/services.py:231 api/system/services.py:247
#: api/system/services.py:280 api/system/services.py:299
#: api/system/services.py:324 api/users/services.py:374
#: api/users/services.py:385 api/users/services.py:396
msgid "The field {label} must be of type string"
msgstr "El campo {label} debe ser de tipo cadena de texto"

#: api/system/services.py:237 api/system/services.py:256
#: api/system/services.py:283 api/system/services.py:314
#: api/system/services.py:342 api/system/services.py:358
msgid "Error while validating the field {label}"
msgstr "Error al validar el campo {label}"

#: api/system/services.py:253
msgid "The field {label} must be an email"
msgstr "El campo {label} debe ser un correo electrónico"

#: api/system/services.py:266 api/system/services.py:293
msgid "The field {label} must be of type array"
msgstr "El campo {label} debe ser de tipo arreglo"

#: api/system/services.py:272
msgid "The field {label} must have at least {min_items} items"
msgstr "El campo {label} debe tener al menos {min_items} elementos"

#: api/system/services.py:275
msgid "The field {label} must have at most {max_items} items"
msgstr "El campo {label} debe tener como máximo {max_items} elementos"

#: api/system/services.py:338
msgid "The field {label} must be a valid URL"
msgstr "El campo {label} debe ser una URL válida"

#: api/system/services.py:352
msgid "The field {label} must be of type date"
msgstr "El campo {label} debe ser de tipo fecha"

#: api/system/services.py:391
msgid "Error while getting the plugins: {e}"
msgstr "Error al obtener los complementos: {e}"

#: api/system/services.py:414
msgid "Plugins successfully updated, please restart the system"
msgstr "Complementos actualizados con éxito, por favor reinicie el sistema"

#: api/system/services.py:416
msgid "Error while activating the plugins: {e}"
msgstr "Error al activar los complementos: {e}"

#: api/system/services.py:445
msgid "Plugin successfully updated, please restart the system"
msgstr "Complemento actualizado con éxito, por favor reinicie el sistema"

#: api/system/services.py:458 plugins/documentInsideSearch/__init__.py:147
#: plugins/documentInsideSearch/__init__.py:168
msgid "The field for the index management doesn't exists in the system"
msgstr "El campo para la gestión de índices no existe en el sistema"

#: api/system/services.py:461
msgid "Indexing is deactivated"
msgstr "La indexación está desactivada"

#: api/system/services.py:574
msgid "The process has been added to the processing queue"
msgstr "El proceso ha sido añadido a la cola de procesamiento"

#: api/system/services.py:577
msgid "Error: {e}"
msgstr "Error: {e}"

#: api/system/services.py:582
msgid "Invalid field definition: {field_def}"
msgstr "Definición de campo inválida: {field_def}"

#: api/system/services.py:739
msgid "System restarted successfully"
msgstr "El sistema se reinició con éxito"

#: api/system/services.py:858
msgid "Cache cleaned successfully"
msgstr "Cache limpiada con éxito"

#: api/system/tasks/elasticTasks.py:199
#, python-format
msgid "Resource %(id)s deleted from index"
msgstr "Recurso %(id)s eliminado del índice"

#: api/tasks/services.py:224 api/usertasks/services.py:147
msgid "Task not found"
msgstr "Tarea no encontrada"

#: api/tasks/services.py:238
msgid "Task stopped successfully"
msgstr "Tarea detenida con éxito"

#: api/tasks/services.py:240
msgid "Task cannot be stopped"
msgstr "Tarea no puede ser detenida"

#: api/types/routes.py:128
msgid "Slug already exists"
msgstr "Slug ya existe"

#: api/types/routes.py:173
msgid "Type not found"
msgstr "Tipo de contenido no encontrado"

#: api/types/routes.py:291
msgid "You must specify the slug and the type"
msgstr "Debes especificar el slug y el tipo"

#: api/types/services.py:59
msgid "Name and slug are required"
msgstr "El nombre y el slug son requeridos"

#: api/types/services.py:72
msgid "Post type created successfully"
msgstr "Tipo de contenido creado con éxito"

#: api/types/services.py:86 api/types/services.py:122
#: api/types/services.py:153 api/types/services.py:256
#: api/types/services.py:268 api/types/services.py:282
#: api/types/services.py:296
msgid "Post type not found"
msgstr "Tipo de contenido no encontrado"

#: api/types/services.py:143
msgid "Post type updated successfully"
msgstr "Tipo de contenido actualizado con éxito"

#: api/types/services.py:166
msgid "Post type deleted successfully"
msgstr "Tipo de contenido eliminado con éxito"

#: api/users/routes.py:296 api/users/routes.py:326 api/users/routes.py:358
#: api/users/services.py:287 api/users/services.py:310
#: api/users/services.py:444 api/users/services.py:456
#: api/users/services.py:467 api/users/services.py:481
#: api/users/services.py:516 api/users/services.py:544
msgid "User does not exist"
msgstr "Usuario no existe"

#: api/users/routes.py:434
msgid "You must specify the password of the user"
msgstr "Debes especificar la contraseña del usuario"

#: api/users/routes.py:438
msgid "Duration must be an integer or false"
msgstr "Duración debe ser un entero o falso"

#: api/users/routes.py:747
msgid "Missing type field in body"
msgstr "Falta el campo tipo"

#: api/users/routes.py:749
msgid "Missing page field in body"
msgstr "Falta el campo página"

#: api/users/services.py:96
msgid "You have reached the limit of requests for this week"
msgstr "Alcanzaste el límite de solicitudes para esta semana"

#: api/users/services.py:172
msgid "You cannot change the username"
msgstr "No puedes cambiar el nombre de usuario"

#: api/users/services.py:176
msgid "You must have at least one system role"
msgstr ""

#: api/users/services.py:190 api/users/services.py:223
msgid "User updated successfully"
msgstr "Usuario actualizado con éxito"

#: api/users/services.py:205 api/users/services.py:485
#: api/users/services.py:520 api/users/services.py:548
msgid "Incorrect password"
msgstr "Contraseña incorrecta"

#: api/users/services.py:216 api/users/services.py:407
msgid "Passwords do not match"
msgstr "Contraseñas no coinciden"

#: api/users/services.py:225
msgid "No changes were made"
msgstr "No hay cambios realizados"

#: api/users/services.py:237 api/users/services.py:329
msgid "User already exists"
msgstr "Usuario ya existe"

#: api/users/services.py:246
msgid "Role does not exist"
msgstr "Rol no existe"

#: api/users/services.py:250
msgid "Access right does not exist"
msgstr "Nivel de acceso no existe"

#: api/users/services.py:273
msgid "User registered successfully"
msgstr "Usuario registrado con éxito"

#: api/users/services.py:283
msgid "Password recovery disabled"
msgstr "Recuperación de contraseña deshabilitada"

#: api/users/services.py:297
msgid "Password recovery"
msgstr "Recuperación de contraseña"

#: api/users/services.py:299
msgid "Password recovery email sent"
msgstr "Correo de recuperación de contraseña enviado"

#: api/users/services.py:306
msgid "You cannot delete yourself"
msgstr "No puedes eliminarte a ti mismo"

#: api/users/services.py:314
msgid "User deleted successfully"
msgstr "Usuario eliminado con éxito"

#: api/users/services.py:323
msgid "User registration disabled"
msgstr "Registro de usuario deshabilitado"

#: api/users/services.py:359
msgid "Account verification"
msgstr "Validación de cuenta"

#: api/users/services.py:363
msgid ""
"User registered successfully. Please verify your account by clicking the "
"link sent to your email"
msgstr ""
"Usuario registrado con éxito. Por favor verifica tu cuenta haciendo clic en "
"el enlace enviado a tu correo electrónico"

#: api/users/services.py:401
msgid "The field {label} must be a valid email"
msgstr "El campo {label} debe ser un correo electrónico válido"

#: api/users/services.py:435
msgid "Compromise accepted successfully"
msgstr "El compromiso fue aceptado con éxito"

#: api/users/services.py:615
msgid "Resource not published"
msgstr "Recurso no publicado"

#: api/users/services.py:628
msgid "Favorite added successfully"
msgstr "Favorito añadido con éxito"

#: api/users/services.py:654
msgid "Favorite deleted successfully"
msgstr "Favorito eliminado con éxito"

#: api/usertasks/routes.py:52
msgid "You must specify the status of the tasks"
msgstr "Debes especificar el estado de las tareas"

#: api/usertasks/services.py:32
msgid "There are no tasks for this resource"
msgstr "No hay tareas para este recurso"

#: api/usertasks/services.py:46
msgid "There are no tasks for this record"
msgstr "No hay tareas para este registro"

#: api/usertasks/services.py:97
msgid "resourceId or recordId is required"
msgstr "resourceId o recordId es requerido"

#: api/usertasks/services.py:99
msgid "user is required"
msgstr "usuario es requerido"

#: api/usertasks/services.py:101
msgid "comment is required"
msgstr "comentario es requerido"

#: api/usertasks/services.py:104
msgid "user cannot be empty"
msgstr "usuario no puede estar vacío"

#: api/usertasks/services.py:106
msgid "comment cannot be empty"
msgstr "comentario no puede estar vacío"

#: api/usertasks/services.py:110
msgid "resourceId cannot be empty"
msgstr "resourceId no puede estar vacío"

#: api/usertasks/services.py:114
msgid "There is already a task for this resource"
msgstr "Ya hay una tarea para este recurso"

#: api/usertasks/services.py:117
msgid "recordId cannot be empty"
msgstr "recordId no puede estar vacío"

#: api/usertasks/services.py:121
msgid "There is already a task for this record"
msgstr "Ya hay una tarea para este registro"

#: api/usertasks/services.py:150
msgid "Task already approved"
msgstr "Tarea ya aprobada"

#: api/usertasks/services.py:154
msgid "You cannot review this task"
msgstr "No puedes revisar esta tarea"

#: api/usertasks/services.py:177
msgid "No unfinished tasks"
msgstr "No hay tareas sin terminar"

#: api/views/services.py:22 api/views/services.py:51
msgid "View not found"
msgstr "Vista de consulta no encontrada"

#: api/views/services.py:118
msgid "View updated successfully"
msgstr "Vista de consulta actualizada con éxito"

#: api/views/services.py:143
msgid "View created successfully"
msgstr "Vista de consulta creada con éxito"

#: api/views/services.py:161
msgid "View deleted successfully"
msgstr "Vista de consulta eliminada con éxito"

#: plugins/birdsAutoConfig/__init__.py:258
#: plugins/filesProcessing/__init__.py:338
#: plugins/minedAutoIdent/__init__.py:163
#: plugins/scheduleSystemTasks/__init__.py:121
msgid "Settings updated"
msgstr "Configuraciones actualizadas"

#: plugins/canvasFormField/__init__.py:67
msgid "Diagrama del cuerpo"
msgstr "Diagrama del cuerpo"

#: plugins/canvasFormField/__init__.py:81
msgid "El campo debe ser una lista"
msgstr "El campo debe ser una lista"

#: plugins/canvasFormField/__init__.py:83
msgid "El campo no puede estar vacío"
msgstr "El campo no puede estar vacío"

#: plugins/documentInsideSearch/__init__.py:472
#, python-format
msgid "%(count)s documents indexed"
msgstr "Se han indexado %(count)s documentos"

#: plugins/filesProcessing/__init__.py:204
msgid "Starting process"
msgstr "Iniciando proceso"

#: plugins/filesProcessing/__init__.py:230
msgid "Processing files. Step {step} of {total}"
msgstr "Procesando archivos. Paso {step} de {total}"

#: plugins/filesProcessing/__init__.py:263
msgid "Processed {size} files of a total of {total} resources."
msgstr "Se han procesado {size} archivos de un total de {total} recursos."

#: plugins/formsDataViz/__init__.py:45 plugins/formsDataViz/__init__.py:66
msgid "Error while processing the request"
msgstr "Error al procesar la solicitud"

#: plugins/liquidText/__init__.py:143
#, python-format
msgid "Se ha guardado el texto líquido en el recurso %(resource)s"
msgstr "Se ha guardado el texto líquido en el recurso %(resource)s"

#: plugins/scheduleSystemTasks/__init__.py:70
msgid "Once a day"
msgstr "Una vez al día"

#: plugins/scheduleSystemTasks/__init__.py:71
msgid "Once a week"
msgstr "Una vez a la semana"

#: plugins/scheduleSystemTasks/__init__.py:72
msgid "Once a month"
msgstr "Una vez al mes"

#: plugins/scheduleSystemTasks/__init__.py:73
msgid "Once a year"
msgstr "Una vez al año"

#: plugins/scheduleSystemTasks/__init__.py:117
msgid "Missing required fields"
msgstr "Faltan campos requeridos"

#: utils/IndexHandler.py:231 utils/IndexHandler.py:250
#, python-format
msgid "Main index %(index)s created"
msgstr "Índice principal %(index)s creado"

#: utils/IndexHandler.py:246
#, python-format
msgid "Main index %(index)s updated"
msgstr "Índice principal %(index)s actualizado"
