# Translations template for PROJECT.
# Copyright (C) 2025 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2025.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2025-02-13 18:49-0500\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.16.0\n"

#: __init__.py:165
msgid "Administrators API is active"
msgstr ""

#: __init__.py:171
msgid "API p√∫blica activa"
msgstr ""

#: api/adminApi/routes.py:49 api/adminApi/routes.py:97
#: api/adminApi/routes.py:134 api/adminApi/routes.py:169
#: api/adminApi/routes.py:213 api/adminApi/routes.py:260
#: api/adminApi/routes.py:294 api/forms/routes.py:34 api/forms/routes.py:87
#: api/forms/routes.py:187 api/forms/routes.py:222 api/forms/routes.py:257
#: api/lists/routes.py:33 api/lists/routes.py:89 api/lists/routes.py:124
#: api/lists/routes.py:185 api/lists/routes.py:226 api/logs/routes.py:48
#: api/records/public_services.py:104 api/records/routes.py:52
#: api/records/routes.py:285 api/records/routes.py:326
#: api/records/routes.py:548 api/records/routes.py:594
#: api/records/routes.py:634 api/resources/public_services.py:44
#: api/resources/public_services.py:104 api/resources/public_services.py:110
#: api/resources/public_services.py:129 api/resources/public_services.py:187
#: api/resources/public_services.py:190 api/resources/public_services.py:302
#: api/resources/public_services.py:401 api/resources/routes.py:109
#: api/resources/routes.py:125 api/resources/routes.py:215
#: api/resources/routes.py:230 api/resources/routes.py:269
#: api/resources/routes.py:535 api/resources/services.py:75
#: api/resources/services.py:154 api/resources/services.py:271
#: api/resources/services.py:744 api/resources/services.py:756
#: api/resources/services.py:816 api/resources/services.py:876
#: api/resources/services.py:879 api/resources/services.py:1072
#: api/resources/services.py:1123 api/resources/services.py:1196
#: api/resources/services.py:1205 api/resources/services.py:1604
#: api/search/public_services.py:30 api/search/services.py:35
#: api/snaps/services.py:96 api/snaps/services.py:142 api/system/routes.py:41
#: api/system/routes.py:69 api/system/routes.py:131 api/system/routes.py:156
#: api/system/routes.py:192 api/system/routes.py:219 api/system/routes.py:246
#: api/system/routes.py:273 api/system/routes.py:299 api/system/routes.py:325
#: api/system/routes.py:373 api/system/routes.py:401 api/tasks/routes.py:52
#: api/tasks/routes.py:82 api/tasks/routes.py:108 api/tasks/routes.py:148
#: api/tasks/services.py:207 api/types/routes.py:98 api/types/routes.py:157
#: api/types/routes.py:167 api/types/routes.py:221 api/types/routes.py:260
#: api/types/routes.py:294 api/users/routes.py:41 api/users/routes.py:85
#: api/users/routes.py:189 api/users/routes.py:228 api/users/routes.py:432
#: api/users/routes.py:476 api/users/routes.py:516 api/users/routes.py:559
#: api/usertasks/routes.py:46 api/usertasks/routes.py:49
#: api/usertasks/routes.py:85 api/usertasks/routes.py:107
#: api/usertasks/routes.py:141 api/usertasks/routes.py:182
#: api/usertasks/services.py:129 api/usertasks/services.py:133
#: api/views/routes.py:33 api/views/routes.py:66 api/views/routes.py:97
#: api/views/routes.py:142
msgid "You don't have the required authorization"
msgstr ""

#: api/adminApi/services.py:13
msgid "Unable to get the default cataloging type"
msgstr ""

#: api/adminApi/services.py:41 api/users/services.py:608
msgid "Resource not found"
msgstr ""

#: api/adminApi/services.py:49 api/lists/services.py:143
msgid "Option not found"
msgstr ""

#: api/auth/services.py:89 api/tasks/services.py:166 api/users/services.py:43
#: api/users/services.py:63 api/users/services.py:81 api/users/services.py:168
#: api/users/services.py:196 api/users/services.py:570
msgid "User not found"
msgstr ""

#: api/auth/services.py:91
msgid "Invalid password"
msgstr ""

#: api/forms/services.py:88
msgid "Form created successfully"
msgstr ""

#: api/forms/services.py:131 api/forms/services.py:152
#: api/forms/services.py:320 api/types/services.py:314
msgid "Form not found"
msgstr ""

#: api/forms/services.py:141
msgid ""
"Form updated successfully. If new fields were added or the type of any "
"existing fields was changed, it is important to regenerate the index from"
" the option in the system settings"
msgstr ""

#: api/forms/services.py:157
msgid "The form is being used by a post type"
msgstr ""

#: api/forms/services.py:170
msgid "Form deleted successfully"
msgstr ""

#: api/forms/services.py:182
msgid "Error: the field cannot have destiny equal to ident"
msgstr ""

#: api/forms/services.py:185
msgid "Error: the field destiny must start with metadata"
msgstr ""

#: api/forms/services.py:190
msgid ""
"Error: the field with destiny equal to metadata.firstLevel.title must be "
"of type text"
msgstr ""

#: api/forms/services.py:194
msgid "Error: the field with type file must have the filetag attribute"
msgstr ""

#: api/forms/services.py:214
msgid "The value of the accessRights field is not valid"
msgstr ""

#: api/forms/services.py:217
msgid ""
"Error: the form must have a field with destiny equal to "
"metadata.firstLevel.title"
msgstr ""

#: api/forms/services.py:248 api/forms/services.py:260
msgid "Error: el campo {field} tiene dos tipos diferentes"
msgstr ""

#: api/forms/services.py:275
msgid "Error: the destiny of the field {field} is repeated"
msgstr ""

#: api/forms/services.py:282
msgid "The field {field} has two different types"
msgstr ""

#: api/forms/services.py:322
msgid " (copy)"
msgstr ""

#: api/geosystem/services.py:71
msgid "Shapes uploaded successfully"
msgstr ""

#: api/lists/services.py:64
msgid "List created successfully"
msgstr ""

#: api/lists/services.py:79 api/lists/services.py:113 api/lists/services.py:162
msgid "List not found"
msgstr ""

#: api/lists/services.py:154
msgid "Error getting option"
msgstr ""

#: api/lists/services.py:203
msgid "List updated successfully"
msgstr ""

#: api/lists/services.py:227
msgid "List deleted successfully"
msgstr ""

#: api/logs/services.py:31
msgid "Log created successfully"
msgstr ""

#: api/logs/services.py:41
msgid "Logs not found"
msgstr ""

#: api/records/public_services.py:62 api/records/public_services.py:147
msgid "id not defined"
msgstr ""

#: api/records/public_services.py:64
msgid "index not defined"
msgstr ""

#: api/records/public_services.py:98 api/snaps/services.py:36
msgid "Record not found"
msgstr ""

#: api/records/public_services.py:155 api/records/services.py:785
msgid "Record does not have processing"
msgstr ""

#: api/records/public_services.py:158 api/records/services.py:788
msgid "Record does not have fileProcessing"
msgstr ""

#: api/records/public_services.py:161 api/records/services.py:791
msgid "Record does not have fileProcessing type"
msgstr ""

#: api/records/routes.py:495
msgid "You must specify a page"
msgstr ""

#: api/records/routes.py:497
msgid "You must specify a block"
msgstr ""

#: api/records/routes.py:499
msgid "You must specify a slug"
msgstr ""

#: api/records/services.py:60 api/records/services.py:118
#: api/records/services.py:410 api/records/services.py:599
#: api/records/services.py:629 api/records/services.py:655
#: api/records/services.py:664 api/records/services.py:705
#: api/records/services.py:739
msgid "Record does not exist"
msgstr ""

#: api/records/services.py:122
msgid "Record does not have the resource as parent"
msgstr ""

#: api/records/services.py:169
msgid "Parent deleted"
msgstr ""

#: api/records/services.py:200 api/resources/public_services.py:305
#: api/resources/public_services.py:378 api/resources/public_services.py:405
#: api/resources/services.py:771 api/resources/services.py:780
#: api/resources/services.py:810 api/resources/services.py:1075
#: api/resources/services.py:1126 api/resources/services.py:1234
#: api/resources/services.py:1403 api/resources/services.py:1574
msgid "Resource does not exist"
msgstr ""

#: api/records/services.py:377
msgid "File type not allowed"
msgstr ""

#: api/records/services.py:417 api/records/services.py:796
msgid "You do not have permission to view this record"
msgstr ""

#: api/records/services.py:461 api/records/services.py:777
msgid "id is missing"
msgstr ""

#: api/records/services.py:463
msgid "index is missing"
msgstr ""

#: api/records/services.py:597 api/records/services.py:627
msgid "Block updated"
msgstr ""

#: api/records/services.py:653
msgid "Block deleted"
msgstr ""

#: api/records/services.py:707 api/records/services.py:709
#: api/records/services.py:741 api/records/services.py:743
msgid "Record does not have transcription"
msgstr ""

#: api/records/services.py:711 api/records/services.py:745
msgid "Record has not been processed with {slug}"
msgstr ""

#: api/records/services.py:728
msgid "Transcription segment deleted"
msgstr ""

#: api/records/services.py:772
msgid "Transcription segment edited"
msgstr ""

#: api/resources/public_services.py:387 api/resources/services.py:1243
msgid "Resource does not have images"
msgstr ""

#: api/resources/services.py:148
msgid "The metadata is required"
msgstr ""

#: api/resources/services.py:237
msgid "Resource created successfully"
msgstr ""

#: api/resources/services.py:259 api/users/services.py:255
#: api/users/services.py:336
msgid "Error validating fields"
msgstr ""

#: api/resources/services.py:266
msgid "Error validating files"
msgstr ""

#: api/resources/services.py:336
msgid "Resource updated successfully"
msgstr ""

#: api/resources/services.py:428
msgid "The resource cannot have itself as parent"
msgstr ""

#: api/resources/services.py:433
msgid "The parent resource does not exist"
msgstr ""

#: api/resources/services.py:437
msgid "The resource isn't hierarchical"
msgstr ""

#: api/resources/services.py:440
msgid "The resource post type is not allowed to have a parent of this type"
msgstr ""

#: api/resources/services.py:455
msgid "The post type must have a parent"
msgstr ""

#: api/resources/services.py:475 api/resources/services.py:497
#: api/resources/services.py:514 api/resources/services.py:530
#: api/resources/services.py:547 api/resources/services.py:564
#: api/resources/services.py:580 api/resources/services.py:594
#: api/resources/services.py:610 api/resources/services.py:629
#: api/resources/services.py:636 api/resources/services.py:644
#: api/resources/services.py:651 api/resources/services.py:694
#: api/system/services.py:230 api/system/services.py:246
#: api/system/services.py:265 api/system/services.py:292
#: api/system/services.py:323 api/system/services.py:351
#: api/users/services.py:373 api/users/services.py:384
#: api/users/services.py:395
msgid "The field {label} is required"
msgstr ""

#: api/resources/services.py:544 api/resources/services.py:642
msgid "The field {label} must be a number"
msgstr ""

#: api/resources/services.py:561 api/resources/services.py:649
msgid "The field {label} must be a boolean"
msgstr ""

#: api/resources/services.py:680 api/resources/services.py:684
#: api/resources/services.py:686
msgid "There is an error in {label}"
msgstr ""

#: api/resources/services.py:703 api/resources/services.py:713
msgid "The resource must have valid access rights"
msgstr ""

#: api/resources/services.py:735
msgid "The field {label} must have a maximum of {maxFiles} files"
msgstr ""

#: api/resources/services.py:851
msgid "Asociated files"
msgstr ""

#: api/resources/services.py:1178
msgid "Zip files deleted"
msgstr ""

#: api/resources/services.py:1225
msgid "Resource deleted"
msgstr ""

#: api/resources/services.py:1355
msgid "Post type does not exist"
msgstr ""

#: api/resources/services.py:1609
msgid "Post type changed"
msgstr ""

#: api/snaps/services.py:59
msgid "Snap created successfully"
msgstr ""

#: api/snaps/services.py:83
msgid "Snap updated successfully"
msgstr ""

#: api/snaps/services.py:94 api/snaps/services.py:140
msgid "Snap not found"
msgstr ""

#: api/snaps/services.py:106
msgid "Snap deleted successfully"
msgstr ""

#: api/snaps/services.py:160 api/snaps/services.py:188
msgid "Error while getting the file: {error}"
msgstr ""

#: api/snaps/services.py:192 api/snaps/services.py:194
#: api/snaps/services.py:196 api/snaps/services.py:198
#: api/snaps/services.py:200 api/snaps/services.py:207
msgid "File not found"
msgstr ""

#: api/system/services.py:57
msgid "Error while changing the value of the field {key}"
msgstr ""

#: api/system/services.py:71
msgid "Error while getting the resources: {e}"
msgstr ""

#: api/system/services.py:110
msgid "System updates applied successfully"
msgstr ""

#: api/system/services.py:126
msgid "There si no default cataloging type"
msgstr ""

#: api/system/services.py:133
msgid "Error while getting the default cataloging type"
msgstr ""

#: api/system/services.py:147
msgid "The default type of the cataloging module does not exist"
msgstr ""

#: api/system/services.py:154
msgid "Error while getting the default type of the cataloging module"
msgstr ""

#: api/system/services.py:172
msgid "Resources schema updated successfully"
msgstr ""

#: api/system/services.py:174
msgid "Error while updating the resources schema"
msgstr ""

#: api/system/services.py:187
msgid "There is no resources schema uploaded"
msgstr ""

#: api/system/services.py:191
msgid "Error while getting the resources schema"
msgstr ""

#: api/system/services.py:210
msgid "Error while getting the value of the field {key}"
msgstr ""

#: api/system/services.py:227 api/system/services.py:243
#: api/system/services.py:276 api/system/services.py:295
#: api/system/services.py:320 api/users/services.py:370
#: api/users/services.py:381 api/users/services.py:392
msgid "The field {label} must be of type string"
msgstr ""

#: api/system/services.py:233 api/system/services.py:252
#: api/system/services.py:279 api/system/services.py:310
#: api/system/services.py:338 api/system/services.py:354
msgid "Error while validating the field {label}"
msgstr ""

#: api/system/services.py:249
msgid "The field {label} must be an email"
msgstr ""

#: api/system/services.py:262 api/system/services.py:289
msgid "The field {label} must be of type array"
msgstr ""

#: api/system/services.py:268
msgid "The field {label} must have at least {min_items} items"
msgstr ""

#: api/system/services.py:271
msgid "The field {label} must have at most {max_items} items"
msgstr ""

#: api/system/services.py:334
msgid "The field {label} must be a valid URL"
msgstr ""

#: api/system/services.py:348
msgid "The field {label} must be of type date"
msgstr ""

#: api/system/services.py:387
msgid "Error while getting the plugins: {e}"
msgstr ""

#: api/system/services.py:410
msgid "Plugins successfully updated, please restart the system"
msgstr ""

#: api/system/services.py:412
msgid "Error while activating the plugins: {e}"
msgstr ""

#: api/system/services.py:441
msgid "Plugin successfully updated, please restart the system"
msgstr ""

#: api/system/services.py:454
msgid "The field for the index management doesn't exists in the system"
msgstr ""

#: api/system/services.py:457
msgid "Indexing is deactivated"
msgstr ""

#: api/system/services.py:570
msgid "The process has been added to the processing queue"
msgstr ""

#: api/system/services.py:573
msgid "Error: {e}"
msgstr ""

#: api/system/services.py:689
msgid "Cache cleaned successfully"
msgstr ""

#: api/tasks/services.py:203 api/usertasks/services.py:118
msgid "Task not found"
msgstr ""

#: api/tasks/services.py:225
msgid "Task stopped successfully"
msgstr ""

#: api/tasks/services.py:227
msgid "Task cannot be stopped"
msgstr ""

#: api/types/routes.py:128
msgid "Slug already exists"
msgstr ""

#: api/types/routes.py:173
msgid "Type not found"
msgstr ""

#: api/types/routes.py:291
msgid "You must specify the slug and the type"
msgstr ""

#: api/types/services.py:59
msgid "Name and slug are required"
msgstr ""

#: api/types/services.py:72
msgid "Post type created successfully"
msgstr ""

#: api/types/services.py:86 api/types/services.py:122 api/types/services.py:153
#: api/types/services.py:256 api/types/services.py:268
#: api/types/services.py:282 api/types/services.py:296
msgid "Post type not found"
msgstr ""

#: api/types/services.py:143
msgid "Post type updated successfully"
msgstr ""

#: api/types/services.py:166
msgid "Post type deleted successfully"
msgstr ""

#: api/users/routes.py:296 api/users/routes.py:326 api/users/routes.py:358
#: api/users/services.py:283 api/users/services.py:306
#: api/users/services.py:439 api/users/services.py:451
#: api/users/services.py:462 api/users/services.py:476
#: api/users/services.py:511 api/users/services.py:539
msgid "User does not exist"
msgstr ""

#: api/users/routes.py:434
msgid "You must specify the password of the user"
msgstr ""

#: api/users/routes.py:438
msgid "Duration must be an integer or false"
msgstr ""

#: api/users/routes.py:745
msgid "Missing type field in body"
msgstr ""

#: api/users/routes.py:747
msgid "Missing page field in body"
msgstr ""

#: api/users/services.py:96
msgid "You have reached the limit of requests for this week"
msgstr ""

#: api/users/services.py:171
msgid "You cannot change the username"
msgstr ""

#: api/users/services.py:186 api/users/services.py:219
msgid "User updated successfully"
msgstr ""

#: api/users/services.py:201 api/users/services.py:480
#: api/users/services.py:515 api/users/services.py:543
msgid "Incorrect password"
msgstr ""

#: api/users/services.py:212 api/users/services.py:403
msgid "Passwords do not match"
msgstr ""

#: api/users/services.py:221
msgid "No changes were made"
msgstr ""

#: api/users/services.py:233 api/users/services.py:325
msgid "User already exists"
msgstr ""

#: api/users/services.py:242
msgid "Role does not exist"
msgstr ""

#: api/users/services.py:246
msgid "Access right does not exist"
msgstr ""

#: api/users/services.py:269
msgid "User registered successfully"
msgstr ""

#: api/users/services.py:279
msgid "Password recovery disabled"
msgstr ""

#: api/users/services.py:293
msgid "Password recovery"
msgstr ""

#: api/users/services.py:295
msgid "Password recovery email sent"
msgstr ""

#: api/users/services.py:302
msgid "You cannot delete yourself"
msgstr ""

#: api/users/services.py:310
msgid "User deleted successfully"
msgstr ""

#: api/users/services.py:319
msgid "User registration disabled"
msgstr ""

#: api/users/services.py:355
msgid "Account verification"
msgstr ""

#: api/users/services.py:359
msgid ""
"User registered successfully. Please verify your account by clicking the "
"link sent to your email"
msgstr ""

#: api/users/services.py:397
msgid "The field {label} must be a valid email"
msgstr ""

#: api/users/services.py:431
msgid "Compromise accepted successfully"
msgstr ""

#: api/users/services.py:483 api/users/services.py:519
#: api/users/services.py:547
msgid "User has not accepted the compromise"
msgstr ""

#: api/users/services.py:610
msgid "Resource not published"
msgstr ""

#: api/users/services.py:623
msgid "Favorite added successfully"
msgstr ""

#: api/users/services.py:649
msgid "Favorite deleted successfully"
msgstr ""

#: api/usertasks/routes.py:52
msgid "You must specify the status of the tasks"
msgstr ""

#: api/usertasks/services.py:32
msgid "There are no tasks for this resource"
msgstr ""

#: api/usertasks/services.py:75
msgid "resourceId is required"
msgstr ""

#: api/usertasks/services.py:77
msgid "user is required"
msgstr ""

#: api/usertasks/services.py:79
msgid "comment is required"
msgstr ""

#: api/usertasks/services.py:82
msgid "user cannot be empty"
msgstr ""

#: api/usertasks/services.py:84
msgid "comment cannot be empty"
msgstr ""

#: api/usertasks/services.py:86
msgid "resourceId cannot be empty"
msgstr ""

#: api/usertasks/services.py:90
msgid "There is already a task for this resource"
msgstr ""

#: api/usertasks/services.py:121
msgid "Task already approved"
msgstr ""

#: api/usertasks/services.py:125
msgid "You cannot review this task"
msgstr ""

#: api/usertasks/services.py:148
msgid "No unfinished tasks"
msgstr ""

#: api/views/services.py:22 api/views/services.py:51
msgid "View not found"
msgstr ""

#: api/views/services.py:114
msgid "View updated successfully"
msgstr ""

#: api/views/services.py:139
msgid "View created successfully"
msgstr ""

#: api/views/services.py:157
msgid "View deleted successfully"
msgstr ""

